FROM python:3.10

RUN apt-get update -qq
RUN apt-get install git -y --no-install-recommends && rm -rf /var/lib/apt/lists_/*

RUN git clone https://github.com/chroma-core/chroma && \
    cd chroma/ && \
    cp ./bin/docker_entrypoint.sh /docker_entrypoint.sh

WORKDIR /chroma
RUN pip install --no-cache-dir --upgrade -r requirements.txt
EXPOSE 8000
CMD ["/docker_entrypoint.sh"]